src/Codecool.CodecoolShop/Models/Shoppingcart.cs
using System;
using System.Collections.Generic;

namespace Codecool.CodecoolShop.Models
{
    public class ShoppingCart
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public List<Product> ShoppingCartList { get; private set; }

        public decimal Total { get; private set; }

        public DateTime CreationTime { get; private set; }

        public DateTime LastModified { get; private set; }

        public ShoppingCart()
        {
            ShoppingCartList = new List<Product>();
            Total = 0;
        }

        public void Add(Product product)
        {
            if (ShoppingCartList == null)
            {
                CreationTime = DateTime.Now;

            }
            ShoppingCartList.Add(product);
            Total += product.DefaultPrice;
            LastModified = DateTime.Now;
        }

        public void Remove(int Id, bool RemoveAllProducts)
        {
            foreach (var item in ShoppingCartList)
            {
                if (item.Id == Id)
                {
                    ShoppingCartList.Remove(item);
                    Total -= item.DefaultPrice;
                    LastModified = DateTime.Now;

                    if (!RemoveAllProducts)
                    {
                        break;
                    }
                }
            }
        }

        public void EmptyCart()
        {
            ShoppingCartList.Clear();
            Total = 0;
            LastModified = DateTime.Now;
        }
    }
}

src/Codecool.CodecoolShop/Controllers/CheckOutController.cs
using Codecool.CodecoolShop.Models;
using Codecool.CodecoolShop.Services;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Mvc;
using MimeKit;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;
using Codecool.CodecoolShop.Daos.Implementations;

namespace Codecool.CodecoolShop.Controllers
{
    public class CheckOutController : Controller
    {
        private readonly IMailService mailService;
        public IActionResult Index()
        {
            return View();
        }

        public CheckOutController(IMailService mailService)
        {
            this.mailService = mailService;
        }

        [HttpPost]
        [ActionName("ShowCheckOutCart")]
        public IActionResult ShowCheckOutCart(CheckOutModel checkOutModel)
        {
            Order order = new Order();
            order.ProductList = ShoppingCartDaoMemory.GetInstance().GetAll().ToList();

            order.FirstName = checkOutModel.FirstName;
            order.LastName = checkOutModel.LastName;
            order.Email = checkOutModel.Email;

            order.PhoneNumber = checkOutModel.PhoneNumber;
            order.BillingCountry = checkOutModel.BillingCountry;
            order.BillingCity = checkOutModel.BillingCity;
            order.BillingZipCode = checkOutModel.BillingZipCode;
            order.BillingAddress = checkOutModel.BillingAddress;

            order.ShippingCountry = checkOutModel.ShippingCountry;
            order.ShippingCity = checkOutModel.ShippingCity;
            order.ShippingZipCode = checkOutModel.ShippingZipCode;
            order.ShippingAddress = checkOutModel.ShippingAddress;

            mailService.SendEmailAsync(order.Email, "Order Details", order.CreateHTMLString());

            ViewBag.OrderTotal = order.OrderTotal;
            return View("ShowCheckOutCart", checkOutModel);
        }

        public IActionResult Payment()
        {
            return View();
        }

        public IActionResult SuccessfullPayment()
        {
            return View();
        }
    }
}

src/Codecool.CodecoolShop/Controllers/ShoppingCartController.cs
using Codecool.CodecoolShop.Controllers.Api;
using Codecool.CodecoolShop.Daos.Implementations;
using Codecool.CodecoolShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Codecool.CodecoolShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        public ShoppingCartDaoMemory UserShoppingCart { get; set; }


        public ShoppingCartController()
        {
            UserShoppingCart = ShoppingCartDaoMemory.GetInstance();
        }

        [Route("ShoppingCart")]
        public IActionResult ShoppingCart()
        { 
            
            var products = UserShoppingCart.GetAll();
            IDictionary<Product, int> countedProducts = products.GroupBy(x => x)
                .ToDictionary(k => k.Key, v => v.Count());
            return View(countedProducts);
        }

        public IActionResult GoToCheckout()
        {
            return Redirect("../Checkout");
        }
    }
}

src/Codecool.CodecoolShop/Views/ShoppingCart/ShoppingCart.cshtml
@{
    ViewData["Title"] = "View";
}
@model IDictionary<Codecool.CodecoolShop.Models.Product, int>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Basket</title>
  <link rel="stylesheet" href="~/css/ShoppingCart.css" />
</head>

<body>
  <main>
        @{
            decimal totalPrice = 0;
        }

      @foreach (var element in Model)
     {
         
        <div class="basket">
      
          <div class="basket-labels">
            <ul>
              <li class="item item-heading">Item</li>
              <li class="price">Price</li>
              <li class="quantity">Quantity</li>
              <li class="subtotal">Subtotal</li>
            </ul>
          </div>
          <div class="basket-product">
            <div class="item">
              <div class="product-image">
                <img src="img/@(element.Key.Name).jpg" alt="" class="product-frame">
              </div>
              <div class="product-details">
                <h1><strong>@element.Key.Name</strong></h1>
                <h2>@element.Key.Description</h2>
              </div>
            </div>
            <div class="price">@element.Key.DefaultPrice</div>
            <div class="quantity">
              <input type="number" value="@element.Value" min="1" class="quantity-field"
              data-id=@element.Key.Id>
            </div>
            <div class="subtotal">@(element.Key.DefaultPrice*element.Value)</div>
            <div class="remove">
              <button data-id=@element.Key.Id>Remove</button>
            </div>
          </div>
        </div>
            totalPrice += element.Key.DefaultPrice * element.Value;
     }
      
    <aside>
      <div class="summary">
        <div class="summary-total-items"><span class="total-items"></span> Items in your Bag</div>
        <div class="summary-subtotal">
          <div class="subtotal-title">Subtotal</div>
          <div class="subtotal-value final-value" id="basket-subtotal">@totalPrice</div>
          <div class="summary-promo hide">
            <div class="promo-title">Promotion</div>
            <div class="promo-value final-value" id="basket-promo"></div>
          </div>
        </div>
        <div class="summary-delivery">
          <select name="delivery-collection" class="summary-delivery-selection">
              <option value="0" selected="selected">Select Collection or Delivery</option>
             <option value="collection">Delivery</option>
             <option value="first-class">Csodás magyar posta</option>
             <option value="second-class">...</option>
             <option value="signed-for">....</option>
          </select>
        </div>
        <div class="summary-total">
          <div class="total-title">Total</div>
          <div class="total-value final-value" id="basket-total">@totalPrice</div>
        </div>
        <div class="summary-checkout">
          <button type="button" class="checkout-cta" onclick="location.href='@Url.Action("Index", "CheckOut")'" > Go to Secure Checkout </button>
        </div>
      </div>
    </aside>
  </main>
</body>
</html>

<script src="~/js/Controller/ShoppingCartController.js" asp-append-version="true" type="module"></script>