src/Codecool.CodecoolShop/Controllers/LoginController.cs
using Codecool.CodecoolShop.Models;
using Codecool.CodecoolShop.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics.Eventing.Reader;
using System.Net.Http;
using Codecool.CodecoolShop.Sql;
using Microsoft.AspNetCore.Http;
using Microsoft.Net.Http.Headers;

namespace Codecool.CodecoolShop.Controllers
{
    public class LoginController : Controller
    {
        private IAuthenticationService _registrationService;
        public LoginController(IAuthenticationService registrationService)
        {
            _registrationService = registrationService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login(Login login)
        {
            if (_registrationService.ValidateUser(login))
            {
                User user = Queries.GetUserByEmail(login.Email);
                HttpContext.Session.SetString("UserName", user.Name);
                HttpContext.Session.SetString("UserId", $"{user.ID}");

                string Username = HttpContext.Session.GetString("UserName");
                string ID = HttpContext.Session.GetString("UserId");
                return Redirect("/Login/LoginSuccessful");
            }
            return Redirect("/Login/LoginFailed");
        }

        public IActionResult LoginSuccessful()
        {
            return View();
        }

        public IActionResult LoginFailed()
        {
            return View();
        }
    }
}

src/Codecool.CodecoolShop/Controllers/RegistrationController.cs
using Codecool.CodecoolShop.Models;
using Codecool.CodecoolShop.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Web.Helpers;

namespace Codecool.CodecoolShop.Controllers
{
    public class RegistrationController : Controller
    {
        private IAuthenticationService _authenticationService;
        public RegistrationController(IAuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Register")]
        public IActionResult Register(Registration registration)
        {
            try
            {
                _authenticationService.AddUser(registration);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return Redirect("/Registration/RegistrationFailed");
            }
            return Redirect("/Registration/RegistrationSuccessful");
        }

        public IActionResult RegistrationFailed()
        {
            return View();
        }

        public IActionResult RegistrationSuccessful()
        {
            return View();
        }
        
    }
}

src/Codecool.CodecoolShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Codecool.CodecoolShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/viewer.css" />
    <link rel="stylesheet" href="~/css/navbar.css" />

</head>
<body>
    <header>
        <nav id='menu'>
            <input type='checkbox' id='responsive-menu' onclick='updatemenu()'><label></label>
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href='/ShoppingCart'>Shopping Cart</a></li>
   
                <li><a asp-controller="Registration" asp-action="Index">Register</a></li>
                @{
                    if (@HttpContextAccessor.HttpContext.Session.GetString("UserName") != null)
                    {
                        <li>
                            <p class="login-response">Logged in as: @HttpContextAccessor.HttpContext.Session.GetString("UserName")</p>
                        </li>
                    }
                    else
                    {
                        <li><a asp-controller="Login" asp-action="Index">Login</a></li>
                    }

                }
            </ul>
        </nav>
    </header>
    
        @RenderBody()



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)

</body>
</html>